"""Baseline: the schema as phases 2-6 left it.

Autogenerated from the models at the Phase 7 commit, so it is byte-for-byte
what `SQLModel.metadata.create_all` plus the old `_add_missing_columns` helper
produced. That equivalence is what lets an existing database be stamped at this
revision instead of migrated into it — `utils.migrations.upgrade_to_head` does
exactly that when it finds tables and no version row.

Every timestamp column here is naive and holds UTC (`utils.helpers.now_utc`);
`db._create_engine` pins the Postgres session timezone so that stays true.

Revision ID: 0001_baseline
Revises:
Created: 2026-08-18

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversation_messages_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversation_messages_created_at"), ["created_at"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_run_key"), ["run_key"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_step", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("status_log", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_run_key"), ["run_key"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_state"), ["state"], unique=False)

    op.create_table(
        "llm_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_usage_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_usage_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_usage_owner_id"), ["owner_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_usage_run_key"), ["run_key"], unique=False)

    op.create_table(
        "runs",
        sa.Column("run_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dataset_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("problem_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("selected_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("health_verdict", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("pipeline_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("run_key"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_dataset_hash"), ["dataset_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_api_key_hash"), ["api_key_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)


def downgrade() -> None:
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))
        batch_op.drop_index(batch_op.f("ix_users_api_key_hash"))

    op.drop_table("users")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_owner_id"))
        batch_op.drop_index(batch_op.f("ix_runs_expires_at"))
        batch_op.drop_index(batch_op.f("ix_runs_dataset_hash"))
        batch_op.drop_index(batch_op.f("ix_runs_created_at"))

    op.drop_table("runs")
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_usage_run_key"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_owner_id"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_created_at"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_conversation_id"))

    op.drop_table("llm_usage")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_state"))
        batch_op.drop_index(batch_op.f("ix_jobs_run_key"))
        batch_op.drop_index(batch_op.f("ix_jobs_owner_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))

    op.drop_table("jobs")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_run_key"))
        batch_op.drop_index(batch_op.f("ix_conversations_owner_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_created_at"))

    op.drop_table("conversations")
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    op.drop_table("conversation_messages")
